---
- name: Flask-Web in Docker 
  hosts: dev
  gather_facts: true
  tasks:
    - name: Установка Docker зависимостей
      become: true
      shell: |
        apt update
        apt install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        apt-cache policy docker-ce
        apt install -y docker-ce
      register: docker_install_result
      retries: 3
      delay: 10
      until: docker_install_result is success

    - name: Загрузка Docker образа
      become: true
      shell: "docker pull atr29031995/flasky"

    - name: Запуск Docker контейнера
      become: true
      shell: "docker run -p 5000:5000 atr29031995/flasky"
      changed_when: false


{% /*
Ansible код который в связке с файлом full_deploy.tf на терраформе, после деплоя сервера и открытия нужных портов, на сервере запускается ансибл плейбук
который устанавливает docker, скачивает docker image из dockerhub и запускает его.
Код терраформа лежит в этом же репозитории.
*/ %}
