#on:
#  push:
    branches:
      - main

#jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Build Docker image
        run: docker build . --file .github/workflows/Dockerfile --tag atr29031995/flask_app:v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 
          password: "&"
      
      - name: Push Docker image
        run: docker push atr29031995/flask_app:v2
