on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build . --file .github/workflows/Dockerfile --tag atr29031995/flask_app:$(date +%s)
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: atr29031995
          password: "&Dec3mber"
      
      - name: Push Docker image
        run: docker push atr29031995/flask_app
